### ISSUE TITLE
About mapping of the variables

### ISSUE THREAD

**Issue by ninboy** [joebeeson/analogue#2]
In a helper named CustomHelper in Cake, we can use in the views the format:
$this->custom->function()
And that is how the AnalogueHelpers works, if you map that to the variable 'time', you can access it like:
$this->time->function()

Now, in CakePHP 1.3 (at least), you can access the CustomHelper using the variable $custom in the view. But using the AnalogueHelper, no $time variable is defined, having to use $this->time

AnalogueHelper should be consistent with the CakePHP framework, and made public to the views the variable with the name in $this->

**Comment by joebeeson** [comment]
It's actually the opposite of that. It use to be that you could access a helper in a view using it's name as a "direct" variable; FormHelper for example would be accessed via $form.

This caused issues where variables set to the view could "collide" with a helper object if their names were the same. The solution was to change it so you accessed helpers via $this->Form, to continue the example. This is the accepted way to access helpers in a view.

This is how the AnalogueHelper currently operates and as it is the suggested manner in accessing helpers it is how it will continue to operate.

**Comment by ninboy** [comment]
I wasn't aware of that. My company heavily uses this kind of approach, in fact everything is based on $html and $js variables.

Do you have any official (or semi-official) docs where I can find this info/announcement? I think I'll have to convince the Leader Programmer in the project about changing this...

Thanks joebeeson

**Comment by joebeeson** [comment]
No problem. The change was announced with the 1.3 release. The CakePHP book reflects this: http://book.cakephp.org/view/1574/View-Helpers at the top

**Comment by ninboy** [comment]
Thanks joebeeson. I'll fork the project and run a bash script to change all the $html, $js, etc helpers variables to $this-> ones.
