### ISSUE TITLE
Remap should not affect HelperClasses themselves

### ISSUE THREAD

**Issue by mgcrea** [joebeeson/analogue#3]
MyHtml Helper extends core's HtmlHelper.
MyHtml->link function ends up calling Html->link.
However with Analogue enabled, i get infinite recursion error, because $this->Html => $this->MyHtml.

Since remap should be optionnal, i can't change anything in MyHtml Helper (using HtmlHelper).

**Comment by joebeeson** [comment]
So all you're doing is creating a `MyHtml` helper and extending the core `Html` and calling `link` against your `MyHtml` (_Which was renamed to what?_) causes a recursion?

**Comment by mgcrea** [comment]
`MyHtml` is renamed to Html, here is an extract from it : http://gist.github.com/720424 Somehow i would like to use Html as MyHtml in my views but i would like to preserve Html to Html in my helpers.

**Comment by joebeeson** [comment]
When you want to call the method of your parent class you need to use `parent` and not `$this` since `$this` literally refers to the current class the code is executing as.

**Comment by mgcrea** [comment]
Yep, that's it. It fixes most of the issues ! I have some circular infinite references but i should be able to fix them. Thanks!
